# Generated by Django 5.2.7 on 2025-11-03 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_producto_categoria_producto_especificaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría')),
                ('icono', models.CharField(default='📦', help_text='Emoji o código del icono', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_texto',
            field=models.CharField(default='General', max_length=50, verbose_name='Categoría (texto)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='crud_app.categoria', verbose_name='Categoría'),
        ),
    ]
